name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello World "Hello Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Bogart"
